### ISSUE TITLE
Exception when writing to Keepass CSV file

### ISSUE THREAD

**Issue by ironss** [scito/extract_otp_secrets#106]
With just-cloned version (git b72157), I get the following exception when writing to a Keepass CSV file

    Exported 22 totp entries to keepass csv file <redacted>
    Traceback (most recent call last):
      File "<redacted>/extract_otp_secrets/src/extract_otp_secrets.py", line 957, in <module>
        sys_main()
      File <redacted>/extract_otp_secrets/src/extract_otp_secrets.py", line 163, in sys_main
        main(sys.argv[1:])
      File "/<redacted>/extract_otp_secrets/src/extract_otp_secrets.py", line 200, in main
        write_keepass_csv(args.keepass, otps)
      File "<redacted>/extract_otp_secrets/src/extract_otp_secrets.py", line 739, in write_keepass_csv
        if count_hotp_entries: print(f"Exported {count_hotp_entries} hotp entrie{'s'[:count_hotp_entries != 1]} to keepass csv file {otp_filename_hotp}")
    UnboundLocalError: local variable 'count_hotp_entries' referenced before assignment

This happens when

* writing to a file, not to stdout
* there are no HOTP secrets extracted from the QR code

From the source code, the problem is obvious:

* `not quiet`, because writing to a file (if writing to stdout, then quiet)
* if no HOTP codes, `has_hotp` is falsey, so `count_hotp_entries` is never set

The same problem would happen if there were no TOTP entries extracted from the QR code

The solution would be to set `count_totp_entries` and `count_hotp_entries` to zero 
* in an else-clause to `if has_totp:` and `if has_hotp:` respectively, or
* earlier in the function, perhaps when `has_totp` and `has_hotp` are set, or just before the if-statements.

This is a minor issue, because the file is created correctly.

**Comment by ironss** [comment]
diff --git a/src/extract_otp_secrets.py b/src/extract_otp_secrets.py
    index acdc9f3..dceea12 100644
    --- a/src/extract_otp_secrets.py
    +++ b/src/extract_otp_secrets.py
    @@ -730,6 +730,8 @@ def write_keepass_csv(file: str, otps: Otps) -> None:
                 otp_filename_hotp = file if has_totp != has_hotp else add_pre_suffix(file, "hotp")
             else:
                 otp_filename_totp = otp_filename_hotp = '-'
    +        count_totp_entries = 0
    +        count_hotp_entries = 0
             if has_totp:
                 count_totp_entries = write_keepass_totp_csv(otp_filename_totp, otps)
             if has_hotp:
