### ISSUE TITLE
Needed libgl1 for Ubuntu 22.04

### ISSUE THREAD

**Issue by joeaudet** [scito/extract_otp_secrets#176]
Ran into the following error:
```
administrator@totp-extract:~/extract_otp_secrets$ python3 src/extract_otp_secrets.py -d -v IMG_3307.jpg
Traceback (most recent call last):
  File "/home/administrator/extract_otp_secrets/src/extract_otp_secrets.py", line 119, in <module>
    raise e
  File "/home/administrator/extract_otp_secrets/src/extract_otp_secrets.py", line 61, in <module>
    import cv2
  File "/home/administrator/.local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/administrator/.local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```
Needed to install libgl1 in order to get it to work. Brand new Ubuntu 22.04 install, only thing installed was following these instructions. Any other info I can provide to help further support this great project?

**Comment by joeaudet** [comment]
sudo apt install libgl1

As soon as I ran that, I was able to rerun the extract and it worked. Prior to even the example you included had that error. Thought it was my QR code at first. Debug function was vastly helpful here. :) Thanks!
